@levorn_api_HostAddress = http://localhost:5019

### Health Check
GET {{levorn_api_HostAddress}}/api/health
Accept: application/json

###

### Get All Customers
GET {{levorn_api_HostAddress}}/api/customers
Accept: application/json

###

### Create Customer
POST {{levorn_api_HostAddress}}/api/customers
Content-Type: application/json

{
    "firstName": "Ahmet",
    "lastName": "Yılmaz",
    "phone": "05551112233",
    "email": "ahmet@example.com",
    "notes": "Test müşterisi"
}